Update feed [ feed_inteno_juci ] package [ juci ]
-------------------------------------------------------------------------------
* 9c1d001 hidefixerror: inverted bool condition
-------------------------------------------------------------------------------
commit 9c1d00159a7098bda72ee254cf80aaa7a06bab73
Author: Sukru Senli <sukru.senli@inteno.se>
Date: 2017-03-17 16:39:37 +0100

    hidefixerror: inverted bool condition

Base directory -> /
 plugins/juci-network-netifd/src/widgets/overview-wan.html | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
-------------------------------------------------------------------------------